---
apiVersion: v1
kind: ConfigMap
metadata:
  name: jitsi-config
  namespace: jitsi
data:
  PUBLIC_URL: "https://jitsi.xrs444.net"
  ENABLE_AUTH: "0"  # TODO: Enable JWT auth for Kanidm integration
  ENABLE_GUESTS: "1"
  ENABLE_LETSENCRYPT: "0"
  LETSENCRYPT_DOMAIN: "jitsi.xrs444.net"
  TZ: "America/Phoenix"
  # TODO: Configure JWT authentication
  # JWT_APP_ID: "jitsi"
  # JWT_APP_SECRET: "<from-kanidm>"
  # JWT_ACCEPTED_ISSUERS: "kanidm"
  # JWT_ACCEPTED_AUDIENCES: "jitsi"
