---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: nocodb-oauth2
  namespace: nocodb
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`nocodb.xrs444.net`) && PathPrefix(`/oauth2/`)
      kind: Rule
      services:
        - name: oauth2-proxy
          namespace: traefik
          port: 4180
  tls:
    secretName: letsencrypt-wildcard-cert-xrs444.net
