---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: borgwarehouse
  namespace: borgwarehouse
  labels:
    app: borgwarehouse
spec:
  revisionHistoryLimit: 3
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: borgwarehouse
  template:
    metadata:
      labels:
        app: borgwarehouse
    spec:
      securityContext:
        fsGroup: 1001
        runAsUser: 1001
        runAsNonRoot: true
      containers:
        - name: borgwarehouse
          image: borgwarehouse/borgwarehouse:latest
          ports:
            - containerPort: 3000
              name: http
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              cpu: 1000m
              memory: 1Gi
          env:
            - name: TZ
              value: "America/Phoenix"
          volumeMounts:
            - name: borgwarehouse-config
              mountPath: /home/borgwarehouse/app/config
            - name: borgwarehouse-ssh
              mountPath: /home/borgwarehouse/.ssh
            - name: borgwarehouse-ssh-host
              mountPath: /etc/ssh
            - name: borgwarehouse-repos
              mountPath: /home/borgwarehouse/repos
            - name: borgwarehouse-tmp
              mountPath: /home/borgwarehouse/tmp
            - name: borgwarehouse-logs
              mountPath: /home/borgwarehouse/logs
      volumes:
        - name: borgwarehouse-config
          persistentVolumeClaim:
            claimName: borgwarehouse-config-pvc
        - name: borgwarehouse-ssh
          persistentVolumeClaim:
            claimName: borgwarehouse-ssh-pvc
        - name: borgwarehouse-ssh-host
          persistentVolumeClaim:
            claimName: borgwarehouse-ssh-host-pvc
        - name: borgwarehouse-repos
          persistentVolumeClaim:
            claimName: borgwarehouse-devicebackups-pvc
        - name: borgwarehouse-tmp
          emptyDir: {}
        - name: borgwarehouse-logs
          persistentVolumeClaim:
            claimName: borgwarehouse-logs-pvc
