---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: borgwarehouse-config-pvc
  namespace: borgwarehouse
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: borgwarehouse-ssh-pvc
  namespace: borgwarehouse
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: borgwarehouse-ssh-host-pvc
  namespace: borgwarehouse
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: borgwarehouse-logs-pvc
  namespace: borgwarehouse
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
