apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: jellyfin
resources:
  - ./namespace.yaml
  - ./jellyfin-serviceaccount.yaml
  - ./jellyfin-deployment.yaml
  - ./jellyfin-service.yaml
