# Jellyfin - Media streaming server
# Provides streaming for movies, TV shows, and music
# Includes dedicated service account for permissions
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: jellyfin
resources:
  - ./namespace.yaml
  - ./jellyfin-serviceaccount.yaml
  - ./jellyfin-deployment.yaml
  - ./jellyfin-service.yaml
  - ./ingressroute-jellyfin.yaml
  # Storage resources
  - ./pv-jellyfin-media.yaml
  - ./pv-jellyfin-tvshows.yaml
  - ./pvc-jellyfin-config.yaml
  - ./pvc-jellyfin-media.yaml
  - ./pvc-jellyfin-tvshows.yaml
