---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - serviceaccount-prometheus.yaml
  - clusterrole-prometheus.yaml
  - clusterrolebinding-prometheus.yaml
  - secret-prometheus-token.yaml
