---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: prometheus-sa
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./apps/prometheus-sa
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  healthChecks:
    - apiVersion: v1
      kind: ServiceAccount
      name: prometheus-external
      namespace: monitoring
