---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{include "craftycontroller.fullname" .}}
  labels:
{{- include "craftycontroller.labels" . | nindent 4}}
spec:
  replicas: {{.Values.replicaCount}}
  strategy:
    type: Recreate
  selector:
    matchLabels:
{{- include "craftycontroller.selectorLabels" . | nindent 6}}
  template:
    metadata:
      labels:
{{- include "craftycontroller.selectorLabels" . | nindent 8}}
    spec:
      securityContext:
        fsGroup: 1000
        runAsUser: 1000
        runAsGroup: 1000
      containers:
        - name: {{.Chart.Name}}
          image: >-
            {{.Values.image.repository}}:{{.Values.image.tag |
            default .Chart.AppVersion}}
          imagePullPolicy: {{.Values.image.pullPolicy}}
          ports:
            - name: web
              containerPort: {{.Values.service.ports.web.targetPort}}
              protocol: TCP
            - name: minecraft
              containerPort: {{.Values.service.ports.minecraft.targetPort}}
              protocol: TCP
          env:
{{- toYaml .Values.env | nindent 12}}
          volumeMounts:
            - name: crafty-data
              mountPath: {{.Values.persistence.mountPath}}
{{- with .Values.extraVolumeMounts}}
{{- toYaml . | nindent 12}}
{{- end}}
          resources:
{{- toYaml .Values.resources | nindent 12}}
          livenessProbe:
            httpGet:
              path: /
              port: web
              scheme: HTTPS
            initialDelaySeconds: 60
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /
              port: web
              scheme: HTTPS
            initialDelaySeconds: 30
            periodSeconds: 10
      volumes:
        - name: crafty-data
          persistentVolumeClaim:
            claimName: {{include "craftycontroller.fullname" .}}-pvc
{{- with .Values.extraVolumes}}
{{- toYaml . | nindent 8}}
{{- end}}
{{- with .Values.nodeSelector}}
      nodeSelector:
{{- toYaml . | nindent 8}}
{{- end}}
{{- with .Values.affinity}}
      affinity:
{{- toYaml . | nindent 8}}
{{- end}}
{{- with .Values.tolerations}}
      tolerations:
{{- toYaml . | nindent 8}}
{{- end}}
