---
apiVersion: traefik.io/v1alpha1
kind: ServersTransport
metadata:
  name: {{include "craftycontroller.fullname" .}}-transport
  namespace: {{.Release.Namespace}}
  labels:
{{- include "craftycontroller.labels" . | nindent 4}}
spec:
  insecureSkipVerify: true
