apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: cups
  namespace: cups
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`cups.xrs444.net`)
      kind: Rule
      services:
        - name: cups
          port: 631
  tls:
    secretName: letsencrypt-wildcard-cert-xrs444.net
