# CUPS - Common Unix Printing System
# Open-source print server with web management interface
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - pvc-cups-data.yaml
  - deployment-cups.yaml
  - service-cups.yaml
  - ingressroute-cups.yaml
