# Ntfy - Push notification service
# Simple self-hosted push notification platform
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - deployment-ntfy.yaml
  - service-ntfy.yaml
  - ingressroute-ntfy.yaml
  - sealedsecret-ntfy-users.yaml
