---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-config
  namespace: jellyfin
  labels:
    helm.sh/chart: jellyfin-2.3.0
    app.kubernetes.io/name: jellyfin
    app.kubernetes.io/instance: jellyfin
    app.kubernetes.io/version: "10.10.6"
    app.kubernetes.io/managed-by: Helm
  annotations:
    kustomize.config.k8s.io/behavior: merge
spec:
  accessModes:
    - "ReadWriteOnce"
  storageClassName: "longhorn-retain"
  resources:
    requests:
      storage: "5Gi"
  volumeName: pvc-8c9fa15b-6fad-498d-807b-42fb9d5a1720
