apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tdarr-config
  namespace: tdarr
  labels:
    app: tdarr
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-retain
  resources:
    requests:
      storage: 10Gi
  volumeName: pvc-0c803f1d-19d2-4684-8202-97609242ea72
