---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: immich
resources:
  - namespace.yaml
  # NFS persistent volume for photos
  - pv-immich-photos.yaml
  - pvc-immich-photos.yaml
  # Sealed secrets
  - sealedsecret-immich-oauth2.yaml
  - sealedsecret-immich-db.yaml
  # PostgreSQL (external, not managed by Helm chart)
  - pvc-immich-db.yaml
  - deployment-immich-postgres.yaml
  - service-immich-postgres.yaml
  # Redis (external, not managed by Helm chart)
  - deployment-immich-redis.yaml
  - service-immich-redis.yaml
  # Helm release
  - helmrelease.yaml
  # Ingress
  - ingressroute-immich.yaml
