---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: romm
  namespace: romm
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`romm.xrs444.net`)
      kind: Rule
      services:
        - name: romm
          port: 8080
  tls:
    secretName: letsencrypt-wildcard-cert-xrs444.net
