---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: romm
resources:
  - namespace.yaml
  - pv-romm-games.yaml
  - pvc-romm-games.yaml
  - pvc-romm-config.yaml
  - pvc-romm-resources.yaml
  - pvc-romm-db.yaml
  - configmap-romm-env.yaml
  - sealedsecret-romm-oauth2.yaml
  - sealedsecret-romm-db.yaml
  - sealedsecret-romm-auth.yaml
  - deployment-romm-mariadb.yaml
  - deployment-romm.yaml
  - service-romm-mariadb.yaml
  - service-romm.yaml
  - ingressroute-romm.yaml
