apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: booklore
  namespace: booklore
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`booklore.xrs444.net`)
      kind: Rule
      services:
        - name: booklore
          port: 6565
  tls:
    secretName: letsencrypt-wildcard-cert-xrs444.net
