apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: booklore-config
  namespace: booklore
spec:
  storageClassName: longhorn-retain
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
