---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - configmap-dashy.yaml
  - deployment-dashy.yaml
  - service-dashy.yaml
  - ingressroute-dashy.yaml
