apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: atuin
  namespace: atuin
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`atuin.xrs444.net`)
      kind: Rule
      services:
        - name: atuin
          port: 8888
  tls:
    secretName: letsencrypt-wildcard-cert-xrs444.net
