---
replicaCount: 1

image:
  repository: registry.gitlab.com/crafty-controller/crafty-4
  pullPolicy: Always
  tag: "latest"

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  ports:
    web:
      port: 8443
      targetPort: 8443
    minecraft:
      port: 25565
      targetPort: 25565

ingress:
  enabled: true
  className: "traefik"
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/service.serversscheme: https
  hosts:
    - host: crafty.xrs444.net
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: crafty-tls
      hosts:
        - crafty.xrs444.net

persistence:
  enabled: true
  storageClass: "longhorn"
  accessMode: ReadWriteOnce
  size: 20Gi
  mountPath: /crafty_web

resources:
  limits:
    cpu: 2000m
    memory: 4Gi
  requests:
    cpu: 500m
    memory: 1Gi

nodeSelector: {}
tolerations: []
affinity: {}

env:
  - name: TZ
    value: "America/New_York"
  - name: CRAFTY_WEB_HOST
    value: "0.0.0.0"
  - name: CRAFTY_WEB_PORT
    value: "8000"
