apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: mealie
  namespace: mealie
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`mealie.xrs444.net`)
      kind: Rule
      services:
        - name: mealie
          port: 9000
  tls:
    secretName: letsencrypt-wildcard-cert-xrs444.net
