# Mealie - Recipe management and meal planning
# Organizes recipes and helps with meal planning
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - deployment-mealie.yaml
  - service-mealie.yaml
  - ingressroute-mealie.yaml
  - oauth2-sealedsecret-mealie.yaml
