---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: rustdesk
  namespace: rustdesk
spec:
  entryPoints:
    - websecure
  routes:
    - match: >-
        Host(`rustdesk.xrs444.net`) &&
        HeadersRegexp(`Upgrade`, `websocket`)
      kind: Rule
      services:
        - name: rustdesk-hbbs
          port: 21118
    - match: Host(`rustdesk.xrs444.net`)
      kind: Rule
      services:
        - name: rustdesk-web
          port: 5000
  tls:
    secretName: letsencrypt-wildcard-cert-xrs444.net
