---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rustdesk
resources:
  - namespace.yaml
  - pvc-rustdesk-data.yaml
  - deployment-rustdesk-hbbs.yaml
  - deployment-rustdesk-hbbr.yaml
  - deployment-rustdesk-web.yaml
  - service-rustdesk-hbbs.yaml
  - service-rustdesk-hbbr.yaml
  - service-rustdesk-web.yaml
  - ingressroute-rustdesk.yaml
