---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: netbox
  namespace: netbox
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`netbox.xrs444.net`)
      kind: Rule
      services:
        - name: netbox
          port: 80
  tls:
    secretName: letsencrypt-wildcard-cert-xrs444.net
