# yamllint disable rule:line-length
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: netbox-oidc-config
  namespace: netbox
spec:
  encryptedData:
    oidc.yaml: AgAhWmwbKGD/6aVy+CRF0voCiNvho/yre5kE0yzrJPjPznXLxUTzcXvcpYhuyeyP0cLTkhOn1emX8CSqkiCRX52BHh0W1HTA25rziVpOUq89bRQG7tWr4pLaxZBivLQSFugY9fVM7LRFQThYBAjkk/OVtehnQLM6oJT603Gn+E7jjpyP7zX+CJc1wZDmaX2FS0xtF5aQXONmf74Torz0l24p1kPLcdPk4sS3bUFMp6yHGuPQ5FKuQyiWLAo9hVd42N7rO5GD9YZ/CkVnAxH9qQGuj18X55osgblw22EYZqm1Uctm/Smg8tUOEwVZ8xc4GC59eEM5PT8nx5wwvyxbpJ/svqvhCmAmgy3QE6MQ5fMdKObFY8LQJBGp4Yh9DmOg3+3uSOO1ugdsNBsccXHa94sZjQ5cAIM76YME60U+p0n4sLiigGAL2X2sungg2pgnOIOXtLWrXVK6bBYXR5PX8+NGf+/LBTMfb1VWFggve2nUjKTYU7DgAbkrSt7C0X1hSMiNg0lT6FKicDL7fvnGYSByWSni+XZ3gv6B9zkatt/wOpPEOYfLRPm+VbL07ngttjC8oIDP+lJR3QPA8n0QaOAe8SnY61AbnBNXkJ6BKydGnFDDCurazCGXdcVAVdCi4ErvlgLNaNoe96f+ziy17Nh2xWm4c3z0gxk89nHQS/YifutpXn6oLCPiX/KrNh+9hmC//tq/cRxiYJJDLXKSUnqzBkGES31T5yd+Rk+BS+K86I2eDY9LLl3YAUZSyRujjGH6y8bgM/OkTEQJmG0hhYfCuZXco5UaNt/8h1A0aYEJvuhywOHHmwnAE+i073LacrPZp/KXjyoQqpsoM7SyTF+nKH2WXPUB5xtHby/jeRvwv2woFDNJEbyAaWv7+3jl/LaQcDi1SJHDqP9Blxs4rnH/C3XMVgq2eTjKXPbHOuxvaV8fKwdd7soAWnFvALECt/OMWrBHq4sBm35YVcS0GM0IQcKremkheTwwtan2DaMuhe0V9O3K5go0Gk+OmBec2pfhyh2PmiSuL4OLRAXwXrg6ohw=
  template:
    metadata:
      name: netbox-oidc-config
      namespace: netbox
