# yamllint disable rule:line-length
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: netbox-diode-plugin-config
  namespace: netbox
spec:
  encryptedData:
    diode-plugin.yaml: AgA+AmHvYX1Fqvm6kQcoMU0YzTRNAueAH1aQRuhAN+yG/jcVna3klhN4wLWGrbPLDd4Al6ErcMCJbcicdB8w0+++ZBAT6SHUW5ieeTHpk4/FkxeRp65cd9KSV1qGFMDcWqkF6m6rBSsQe9r/RzEVxa3DilHNOz+NQYPBgT3aMiIl9kt+BLudm/b6ovK8H9Ddx1QRG1BiSQI0kE8KLaE5UTEJ39RkxY+fkSbLGKMr206vJ4nbpJdN6++GF3wP7hofybWGquk+NG865o4EgkcMOPX/kdPCkadmA0iZ/Ey8lp/HIzwG2d6CV8CdWlXjJztYun0pGouzVpHZqMh/ukKsay9Im5PVubCXLCcjLJg3hZmBGiatGTDk6SgJVslCRAtvw7osYqrjKvCCZRntbryrMc4N7sb661EUM4+BHzK0sS8ttSyIfQ2F0XE+KGjpoCW2TkezV0ryt40dJBUVSBsnOx5how2VB/vbk4shXnoIsCjU09iQtaZ3OnSA57a8yCY91n4d+sPjEIhmEgW/Rn/iph9tKDNBtQwFNla1vrOI7HTP5ZcwLNsBwNg2wlXA23NqsFkqKKeKi6OoMbVi0rZDGwQpXtKnzyMVh9F2ZEkViFVjU+TBLh4UH7w3sqCBpTNQQvbGn90YnhWMM+20mxvXvn/xBe5eoYLWbOmLFQmvwStrJsVv3Gj/p5W+/UZjEQWvVoOJHGwJwRGsqCdk/meABW9/68IArKmtHrJpGAy5qppxrUZTY5HqmTjHFktEp9eEhEtysdE/FYzqH9vR1I0MBu+u8fxjHiGoo2YWV1nCy8Spp400Csmt4hRmMG+pjPUrhMlS4YRlYzSBr/Ciawl09CNpnQ8gf/QjbUuMBJGLpLyogh7RQhDuNwkn+9eQsy9QIE46SJUGQ7iogtqBcspu7bI1MKEorTma4o1bPUFNykcpO4Sv82pbuCGCC6jLNjfSOwZwgchql1W/HqnJy1+/xgE=
  template:
    metadata:
      name: netbox-diode-plugin-config
      namespace: netbox
