# yamllint disable rule:line-length
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: netbox-diode-plugin-config
  namespace: netbox
spec:
  encryptedData:
    diode-plugin.yaml: AgAcNTJaG8nb4PWX1Ij/vwVinXigcoz8e8dNG/MvTOBLM6Dn4w6lOx7/wBOoL1gNays/FKAs1IqvDeuZKdrzkUTY2ZC5vOqsTaAn61bcPeyyAlNJHUmkBphcqz1rWvFHlWXIy2i0Bjt+EMFo9vNBPkDRZywwwm5pZQLWcCpFiMw+b9GK0Y0b+3HVeDTXvJX2ue7jBJhrXS+WU60Q5ywTqx9Q+3OVPNbva+A/4KIUv9AzkWj74pMhP27jfstxRpZtkduOxeJuTsgXcDi0XUY1pmCFzzcWdmfq/uUBLEJm891Zjz+Dl1oA7WpErublZE274EjZf4q4EXai9cQzG6pwY0XFcUEj/4T4KHa2ruhKgLHRNdHbQFpPjT4gpkfYuGZG0R58W91KcVdfGIzbjDIMwRL1xs2lCiyn/eC7vzDfw2l6J0RA09hFTHvce9WTG7dowNB5ad/BsPYpiGJowHY1SHatpcvlG7faCJucg0qV1Ixd9Cek/HC53bgIqr9exl7iHAwDpjk0yI7I2ZEZyPQE/tTyG+ikkiqwpE5vonDJ0Q3bn2TRLQCnPX7JAfo9uJaUY2v4WBwCd+tSth25HOMo1Me/+Kw6J/cohKIOnZPhXgKthdZAn6UdpdhpU1ZRNwMCdZidAMJDGoFfUPL+CkBPRH/jZOGSpiuNq1IeyfXFocHQlyCogkO2i3JQp7334U8keujyoagR9NITyUlrRAtkyRpE3P8xjhmLaY8BarW8LEKGqlegaQFxOjkbGy642sGlz9/kVwiNzTV29286H5AElRfs4ROJcxdoSRL3Q2j6mpMHVK2gL/SpxlWb2+GrCK+t3DvTkl5Ye8lcFv8qge6nQBY1kasfI3fd89OLrC1Y6twRcye/kJQixzohclH7ONZ+KYrRPV7Bqd4tSMvxraRYSIwGB43+qIJCful1AE9iZs/Z0ikqz8NmLULzIGSbjRf5IyINHCEMB79PGZstnqLiVja0jm5rliWbD7Zqv6nBUA==
  template:
    metadata:
      name: netbox-diode-plugin-config
      namespace: netbox
