# yamllint disable rule:line-length
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: netbox-diode-plugin-config
  namespace: netbox
spec:
  encryptedData:
    diode-plugin.yaml: AgA1WsyUoF9vVWxS1hOjSrY3EbZyLFgkCqEahNXKVfgWGqOElalQIklS8O25G7T80LZLCLjJh9VVDfs122M0T0c+yHZyC7eXlkqrbSGoQMOueVPfdU3TjNVInJb6hTSR9FohV1fLQ7QZWHuWsbVwZnGDe9gRybcYxlgH2Y9Rg5H1g5qAU+806e2iDKXPvcJo3sl9f0z14Siafay+4WH3FVSEemX8T3dIL7chqpKk69G8KLF1jYMEW1p+Se03ZieHr9Gei1bIyfPacaXqrjFZtd2bDyPZBeYRMuMw+V1IhtIUPoa0WVJ9VhcXHKIGgC+qMZL5aEa6nvAIrM9ERY0k7FELKXWEO8sZrsZlA9kSshpYkVNiHQHDUvSnpn9nCk1i0Fz/nWfmfVchial7hGMB0VI5X2UNPurLnwzZa074nwajDBwGs2zu7E/TJ70T5E5KijHOY5yYnfooThpIyWWJhDa+8YbM7z0E9i//WC5oK5c1isvEON7rMKUUiv01IppAv4MCae3g5iFt6GxIyrfW8AgADKXJgkLBa7jayQAXXTL78e0dDYWX0shfsnyVbJLvC7qngnN9qO+AdRvASLqdEDRJUCn8nc9YDMp1mQiyGYlAKBY3R5XR1Ne18LpNDqv56Wqy+I7B9mR7kBT/uxGLwOBbssZ2dcOzQp2ZxQC6Xja7Qi1cMl1ul0uYrc/N+w0GvhaDB0KatRHpipfOkq9/WAuDTswF6RBoiciq2De+Zrn50oUoZC3n70Fi/ai129I/8Wbr+BBvo2WYN32WiT9QYdWrcjLolsC0r3eiApI06EJKEQ8TKv1uiAcRpwtczgmnJmMXKK96rcEB0TDe1g4tMmWmPcu0m8gHfO+G6C+8aq8Gmrd+9u6wwF1AJ4+/SKOwuwC8FBiM/mmlZ07/9gBg08fXPoq5YU0+huRmtjloRwaDuPSPx/u1BCNwOb7mmrj7e0dG03SBwpWMKOQ=
  template:
    metadata:
      name: netbox-diode-plugin-config
      namespace: netbox
