# yamllint disable rule:line-length
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: netbox-oidc-config
  namespace: netbox
spec:
  encryptedData:
    oidc.yaml: AgBkwmKIuVRYNOibIjzYWEBELRdZNtjhUFC4Tm0K5gHvQhWx63hX244fRAr7q6n1q92JmyZGrpBn1l/bT0nJ5vx7jVoLxiyMUiGnwqMZHOpnUNSt1pCzazpuHb2xnnYYlLvdR/P7dGcrFVuGXKbub1rY3/qV4TJ53u9YqBY9mZDTGeN09J1tcQpGq+wyj7hiFt4EWzj6bWGsbxVKdnJnpeqCzUbM/lvQK+pQNux5rR2ELUrCBJxS7uo5aqksX8BYL/kDT8BZeyz0KoFYJvjEXBOT310nh4yI+vDPL3sVUwkTE9UJCCCer8Dgi+FlLMa+e9/w/33A1ysWUx8cnAY0931R8KMXAIU97LmlVVNZu8C2cJDdv8KbvFc3Or2MiNU8pxJN9fXXAM+rf6HCkJoBZynMQGvGZd5q+Rc5cuBMwE/OfRCTde9s2ceoQLWJUB4+Cxb9B6CoiQxCuUlVreBNKEL9iAkaWX2U8NW62H5Xz8Yo2gYbBITNS6MBcz4eVb620fwGb3hYAxafSDyVlH0C954Q/IP7XhstNlTTiethSpJgpmzICh/GD1LZRILl0z5qnm9cQ7aQmBqriXVNUDwBk3GGiqGtiuZHnbJl5X5QBpE9F7OeQ8GNbNNios+Af+zVkh5lyHUcm8n36tj0etN2+NFmJ9uNKInb6dqkkriXTbulUt8qsyB+m+jaL8k0OYRkHZkDRADAVlBIGEoT1a804cF6NKBwW/vfj/aSYBQoS2a6rEmHgjeJsPttmWUbwM95uoxC/FgwnTNZVLa2umU5Tm6esvinA6nheuBWi5ozWs339koNHOseAIoyOCKob2W/Os1hRDn4uJ5QcvxZElL5/v9L/AKATh84KNdGM91rEFp379Tlnu+1QWSBH7mvqq1cJbBuMZiiH9Sp6NQm2k5RRYWMw4tfITiYVBruRPwItQx75TZhjfQnanGaJx+lCbFzy2oHiHNs2BKbwSzf7OdHQ+n4ZFa2h3sx4knFPEcuLLihxd9vonC5AAObSXbTOKC5sJq+EHkUSHlMQqNyKkdKCw==
  template:
    metadata:
      name: netbox-oidc-config
      namespace: netbox
