# yamllint disable rule:line-length
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: netbox-oidc-config
  namespace: netbox
spec:
  encryptedData:
    oidc.yaml: AgAvd8+7HX7khaXQwATSYFr8z/mpeeRD5PIB9FjaRmcz2csIZXiSnkx0AmjlHFxyMuXOOg+4diXff8Y2XX/q4QvYWaDTYUp8dZkxhHc36nwXjpv4JSKsFZZ7t9pDWCAAQjuo2MGMa5xWtNAlnx0idbn0Qwm3S8lvhYuwEc8JONUN/COxl/rDF6i4DDlcZ0n/YtkpdKuAgiqKKR49wFkBuyDciCjyH3IYmbEHj7NYmJSoUcPd1mqCjMPrCs2EUV1ec6ulXBYUK4DTG6Kaabl/l+peSXT6Nd+SpsxywuUabGVd+N0r49husLOmbhmX/d02LKs3vNul4QpnEahr7mjy3k6WTpRJKHe3VjOeFu9eINulD/PQTd28LZNXXTkzf+ZCfEKpr8ws+dV19LmuJM4e9Hw+m6QXOxB1vYqBnmasr0fnHVFSpgtXU9CDevYelLHXP+qfscgbQvfU0W7Qq0gCipUyjdQoENJZKaMfxUV+Vd1G1N9oWm+zjdnJwXwin0odfCMhMb5mmcYfTG7XfVAdR/BsDglJZsvVGMa8j4cjtutnXtUNBm9MkrgxcNrMB+1TRKwiuiJF9Vws/oudzePrfdIOxzzLOV5S+MeIH8lFb2Q/3Fj2d4WPnsbcaduawZ3PWYRhI088B5rb2ZNLsXPj8Xad5kDSyi5v1lT8ym6xs5+7fs4+A5X0XwGZdNS5d/eanVHYlOeAcvmZsC5SyRjxOqFcWRz4vsOIgX25xO8OlRQc16dDLOQC6AVDpGNFpz7TjLUq/yP7xy+VBxF1LxUbPxFXKlU+vsDWxI8Mp1VjyXQx1sfgOxfKJEL63HtyN9sFypUAHe+f8ghYJ/BJFxt6CEu3cxHSpAkVOGxuKFsx/alj8BjbfWdZcW7BjQoHEHnvf1V4D2P0bhCkpVrPILij6u+X1enTYbNTjhXtOl6NgTebcUzezhT6kY6i17Qg6+bMXCvfiPJbSWlrBP0bBtntNDL13TPH
  template:
    metadata:
      name: netbox-oidc-config
      namespace: netbox
