# yamllint disable rule:line-length
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: netbox-oidc-config
  namespace: netbox
spec:
  encryptedData:
    oidc.yaml: AgCZTJ3zPG1bvukOBATnWu7/QATCxazE1Hhf0OTvT993b3zIAzuCa7vnQ4lvnJjATymwR6U6IIm8x/xKtiITvC3oXr4XQjZaLmAOut459ZcUtDVhEpCg2dZb80xf+baXKyTTikURkTFk6h6Xx9BjTLqn64Pu5GCyfaFo1OFDqakkBr6irWtm7b4jIuyBTfW2t4Khusqr2G9G2GCRbbEW5Ul/by4WXVBtRNrLQ2zq/3HxpVMHbMmVOtmoM8+/upK+GOrvC12xWV6Am+w0oqQlIEw4DESSMRfhDYvPNZ4WWMqObnhy7sTF6H4bCVJ1RhrSy2u6Slxi1vUofa4DPuxzkBLKcy08o2+DZpPhZVlM1a3Ie8tYdu28f2fL/zcFCXoxs1rBj/3LLfPPwtjom+ShzSnz+JmgqEHWl3kwImZw7ZXNcE2ijuBNZ24w1S4uioJKP9vgahgqpGPhVV+Y2aCe8qndDyyF4Ib24+9RY5hSOcQx4Oz4aN6DvE23HGVnkl/Ee9b9FIm5xo7qbzSIeQcfhrczhGQEIW4coEmj4/3itopXVm6JXpByidXqQDfboRAl1ZHcaILhdYUZXirg+0biRx7fRt0LkVEwcbumr8M94nmnbYh5DURRmD0hLJoiHE/WrfzUGCd0s+5lXEgEQpBGORNodyCZxsMNO/uwMPY+GkJ1x1lzIT+SAdHMUIpM5eHVwc95HdT659bvrbzJXU8FjZThk1ZRmZAwLdFwml6cxxVHcxFJfkNB9wcARN4Wz5OQ4sIacgTNQvUGfTNbBwFYZuR3elMMzNC9lDEmclrVXLKX58kPb0k1SbMMXTy/KuY2E4F8W4l0gFiQuUf01YeEMRLql1JFYJwmEdX5y1k8ooS/c4nEb9TICTHm3TY9nYdl/ZTP06oaY/L4tdIvaBxeJU6oqTL4Tx3JzZA/bDBMaBUE6y9FblTZuYmpbQa/UDUZEXnywkiFca/afzgXI9aKZfm63gki0BNydRmE1RZVWB9k2UchzPvBsNtGjXzrRx7MVYhSDE+oTVWz9PGpaCncb3WtvsmCRleQPOA=
  template:
    metadata:
      name: netbox-oidc-config
      namespace: netbox
