---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ip-masq-agent-config
  namespace: kube-system
data:
  config: |
    nonMasqueradeCIDRs:
      - 10.244.0.0/16
      - 172.21.0.0/16
    masqLinkLocal: false
    resyncInterval: 60s
