---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: omada
resources:
  - ./namespace-omada.yaml
  - ./deployment-omada.yaml
  - ./service-omada.yaml
  # Storage resources
  - pvc-omada-data.yaml
  - pvc-omada-logs.yaml
