---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: diode-agent
resources:
  - namespace-diode-agent.yaml
  - serviceaccount-diode-agent.yaml
  - configmap-diode-agent.yaml
  - sealedsecret-diode-agent.yaml
  - cronjob-discovery.yaml
