---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: diode-agent
resources:
  - namespace-diode-agent.yaml
  - sealedsecret-diode-agent.yaml
  - configmap-orb-agent.yaml
  - deployment-orb-agent.yaml
  - configmap-device-list.yaml
  - cronjob-device-ingest.yaml
