---
apiVersion: v1
kind: ConfigMap
metadata:
  name: garage-config
  namespace: garage
data:
  garage.toml: |
    metadata_dir = "/var/lib/garage/meta"
    data_dir = "/var/lib/garage/data"

    db_engine = "sqlite"

    replication_mode = "none"

    compression_level = 1

    rpc_bind_addr = "[::]:3901"
    rpc_public_addr = "garage-rpc.garage.svc.cluster.local:3901"
    rpc_secret = "${GARAGE_RPC_SECRET}"

    [s3_api]
    s3_region = "garage"
    api_bind_addr = "[::]:3900"
    root_domain = ".s3.xrs444.net"

    [s3_web]
    bind_addr = "[::]:3902"
    root_domain = ".web.xrs444.net"

    [admin]
    api_bind_addr = "[::]:3903"
    # TODO: Generate secure admin token
    admin_token = "change-me-to-secure-token"
