apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: garage-s3
  namespace: garage
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`s3.xrs444.net`)
      kind: Rule
      services:
        - name: garage-s3
          port: 3900
  tls:
    secretName: letsencrypt-wildcard-cert-xrs444.net
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: garage-web
  namespace: garage
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`garage.xrs444.net`)
      kind: Rule
      services:
        - name: garage-web
          port: 3902
  tls:
    secretName: letsencrypt-wildcard-cert-xrs444.net
