# Garage - S3-compatible distributed object storage
# Provides S3 API for application storage
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - configmap-garage.yaml
  - sealedsecret-garage-rpc.yaml
  - statefulset-garage.yaml
  - service-garage-rpc.yaml
  - service-garage-s3.yaml
  - service-garage-web.yaml
  - ingressroute-garage.yaml
  # Storage resources
  - pvc-garage-data.yaml
