# Audiobookshelf - Audiobook and podcast server
# Manages and streams audiobooks and podcasts with web interface
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - deployment-audiobookshelf.yaml
  - service-audiobookshelf.yaml
  - ingressroute-audiobookshelf.yaml
