apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - pvc-audiobookshelf-config.yaml
  - pvc-audiobookshelf-metadata.yaml
  - deployment-audiobookshelf.yaml
  - service-audiobookshelf.yaml
