---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - .gitkeep
  - gotk-components.yaml
  - gotk-sync.yaml

patches:
  # Allow Flux system pods to run on memory-constrained node
  - path: tolerations-patch.yaml
    target:
      kind: Deployment
      namespace: flux-system
