---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apprise
  namespace: monitoring
  labels:
    app: apprise
spec:
  revisionHistoryLimit: 3
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: apprise
  template:
    metadata:
      labels:
        app: apprise
    spec:
      containers:
        - name: apprise
          image: caronc/apprise:latest
          ports:
            - containerPort: 8000
              name: http
          env:
            - name: APPRISE_STATELESS_URLS
              valueFrom:
                secretKeyRef:
                  name: apprise-config
                  key: ntfy-url
                  optional: true
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
