---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: apprise-config
  namespace: monitoring
spec:
  encryptedData:
    # yamllint disable-line rule:line-length
    ntfy-url: AgAkunTSSvfC1l+xrUPnq+GKwNuxM2BE9jPnudCn68bige87oJ0/3AFBXVups1Bik+P1QmpQHQreRRBQM157bbdo54xTDwpHX/kUY2CJhrLYwSQEgMnRgMs+zmEX1Ix7QVW/23dG6EIycAwNfDcWQLq8ZniwMWK5ymSaUyCj5vCybXSNYpWiG0XSF+ds9YsY5u/J3JwW3GubFfp/db/P6nWs9awurP/5M8aiZOp7IkEmTatjn1DTaJylk0OGZJ5KB/yO2J3ucLXwTX+jfzpCOraj6RKN3Myrxjob2a5X7BWK4RcZZclAz+zmV2Cojsf9udkBTPzfO5mPVD4mnV1yEzvZy4VfeEShRSf9YUQATup9rM9CxEGFEmN6KNsv5cm+w+SOgr0RgCI+cA3PDz/NT2oA6j/znX1yOIUdhzdQ3RJUJ8hqVcUyXuVoGyKotFljrQzSFsgNPo6gA2Ml2WCJEbWw1yMGqxEfLfuoXVlMwZD67HgXJ6IJRXdyA+341If0BGa/o/iNHsg8E1BRIekYfWedsuuJ8fN7sZHvTG4dkb+NwUO1UxaNRkyqHsOM15sP8yQpBY7Ucdad/JSYwRun5Dn0De9sJtO/tUDTN6OeU+XiaIYIT9QjuHMaeHPIS1v5JMOQyVg2C/MSKvcVINGJd4026A8Wk1Gr61DmyaqGp1E1eY+asagp5azoR2ON17RYPDiIhB1FcAG3FdLwZIw1DagREAteR0ZRz+B9vYVlEw89bB5H3JAx61g3+veV8ptTmucL3teZNikNnyhKAZBiZDDr/QvDuux4FKfGDXA4+4TeXqXHI2SDy/jzh4Zcs6ZGSdqbUWZbnLNeyqCt
  template:
    metadata:
      name: apprise-config
      namespace: monitoring
