---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: apprise-config
  namespace: apprise
spec:
  encryptedData:
    # yamllint disable-line rule:line-length
    ntfy-url: AgAUHwVDVE6RqRG4bluhiQ0iXAiq0OpV77m9p7IOxfztVj0qO77axT4T1uMBaeC/Nx5J/5QNgpUqFISAvL/deQ/tMC4sgtHqvCLuiHwGhEQGx6F6aUSvD/BoE4ILoUU1YmhnBTQVzXx+V46W9yy72RPvr9ZMoqX3TzClYhqEFCK8s6pIVLgmyq0B3p78SC4ZG3tkGfDwx6M094T4+9AAsjiq1MXgUX05MrgMyvywzCvQkf5RZpUK77wSpf2FevHmQn2LVKAybt81YbnImrjh1wUmi2pTjjgHQ7V36uns1m274yxSOrmddjwHC6o0imnvUOCokNrbITKUDvY60pkAoRhAyDzzZ1o63LV/JrSA+III1w76CxCaQwU4rKm61FsIfbhPLQxdFsoIFGJeFFUgH/FG69P57zKQtUf3nDQmFjpZraGER071tTJElntqDoCbV/ZHu8Rfj/ZhAGLQ8Ib6JPJZO92OoBtBJBJatyor39KXt6XLaso/GeH0Dz+L0Y1j038axYuCx6BFtUR+EwlhPr6QPVxr0iPr+ukCgyKFyzKzbLkaJMDxKBZR5Pn1H9NhnwZzINBe8uWv2RcIJvZNmkr9Xw32ThOHZ2BUIBOjQDSAx3oHaJgiEkbOyFfFzX6G0bXCHYVNtXbq4y2xukSUZk8YQoSrixbCIqjFv03ifA/2vMv6pYlnLFjoj+nU/GQyFwph9AP/f4CTLd+MWfvf/eGXRPkrrscdqh4beGiH+yeAiHqAVmRBoxmJmqgfvg5EJ/34bHAdblTAym9EIiGkhJ6gRnDSZdXwNcaAgduU+x1Rx3Me
  template:
    metadata:
      name: apprise-config
      namespace: apprise
